package GUI.Owner;

import Dao.UserDao;
import Model.MenuModel;
import Dao.MenuDao;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.UserModel;

/**
 *
 * @author user
 */
public class ManageUser extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    UserDao dao;
    DefaultTableModel dtm;
    UserModel modelG = null;
    String[]  kolom;
    public ManageUser() {
        initComponents();
        dao = new UserDao();
        
        tampilData();
    }
    private void tampilData(){
        String[] kolom={ "Id User","username","Nama "};
          dtm = new DefaultTableModel(null,kolom){
              @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
             };
          
        for(UserModel model : dao.getList()){
            String[] row = new String[3];
            row[0]=model.getIduser();
            row[1]=model.getUsername();
            row[2]=model.getNama();
            
            dtm.addRow(row);
        }
        jTUser.setModel(dtm);
        jTUser.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTUser = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jBDelete = new javax.swing.JButton();
        JLid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFnama = new javax.swing.JLabel();
        jTFUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("Username");

        jTUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTUser);

        jLabel4.setText("User");

        jBDelete.setText("Delete");
        jBDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteActionPerformed(evt);
            }
        });

        jLabel3.setText("ID User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(JLid, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFnama, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTFUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addComponent(jBDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel4)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(JLid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addComponent(jTFnama, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFUsername)
                        .addGap(34, 34, 34)
                        .addComponent(jBDelete)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTUserMouseClicked
        // TODO add your handling code here:
        
//        int i = jTUser.getSelectedRow();
        String id = (String) jTUser.getValueAt(jTUser.getSelectedRow(), 0);
        UserModel model = dao.byId(String.valueOf(id));
        modelG=model;
        
        JLid.setText(String.valueOf(model.getIduser()));
//        JTNama.setText(model.getNama());
//        JTHarga.setText(String.valueOf(model.getHarga()));
//        JTStok.setText(String.valueOf(model.getStok()));
//        JCBKategori.setSelectedItem(model.getKategori());
//        JTDeskripsi.setText(model.getDesc());
//        
//        String id = jTUser.getSelectedRow()+1;
//        UserModel model = dao.byId(id);
//        modelG=model;
//        
//         int i = JTBMenu.getSelectedRow()+1;
//        MenuModel model = dao.byId(Integer.valueOf(i));
//        modelG=model;
        
//        jLabel3.setText(model.getIduser());
        jTFUsername.setText(model.getUsername());
        jTFnama.setText(model.getNama());
    }//GEN-LAST:event_jTUserMouseClicked

    private void jBDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteActionPerformed
        // TODO add your handling code here:
        try {
            String id_user = JLid.getText();
            dao.delete(id_user);
            tampilData();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
           tampilData();
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "terjadi kesalahan " + e.getMessage());

        }
    }//GEN-LAST:event_jBDeleteActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLid;
    private javax.swing.JButton jBDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jTFUsername;
    private javax.swing.JLabel jTFnama;
    private javax.swing.JTable jTUser;
    // End of variables declaration//GEN-END:variables
}
